# 1. Transverse field Hamiltonian

In [71]:
import numpy as np


paulix = np.array([[0,1],[1,0]])
pauliz = np.array([[1,0],[0,-1]])
identity = np.array([[1,0],[0,1]])

N=8
J=1
h=1/2
term1=None
for j in range(N-1):
    term_j = None
    for i in range(N):
        term_i = None
        if (i == j or i == j+1):
            term_i = paulix
        else:
            term_i = identity
        
        if term_j is None:
            term_j = term_i
        else:
            term_j = np.kron(term_j, term_i)
    if term1 is None: term1 = term_j
    else: term1 += term_j

term2 = None
for j in range(N):
    term_j = None
    for i in range(N):
        term_i = None
        if (i == j):
            term_i = pauliz
        else:
            term_i = identity
        
        if term_j is None:
            term_j = term_i
        else:
            term_j = np.kron(term_j, term_i)

    if term2 is None: term2 = term_j
    else: term2 += term_j

##
J,h = 1,1/2
H = J*term1+h*term2
print(f'Hamiltonian: {H}')
eigenresult = np.linalg.eigh(H)
print(f'eigenresult: {eigenresult}')


Hamiltonian: [[ 4.  0.  0. ...  0.  0.  0.]
 [ 0.  3.  1. ...  0.  0.  0.]
 [ 0.  1.  3. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -3.  1.  0.]
 [ 0.  0.  0. ...  1. -3.  0.]
 [ 0.  0.  0. ...  0.  0. -4.]]
eigenresult: EighResult(eigenvalues=array([-7.64059255, -7.63473266, -6.46616949, -6.4603096 , -6.10506669,
       -6.0992068 , -5.71456595, -5.70870606, -5.3545768 , -5.34871691,
       -5.05324285, -5.04738296, -4.93064363, -4.92478374, -4.8274015 ,
       -4.82154161, -4.68779937, -4.68193948, -4.54014289, -4.534283  ,
       -4.18015374, -4.17904009, -4.17429385, -4.1731802 , -3.87881978,
       -3.87295989, -3.81905094, -3.81319105, -3.65297843, -3.64711855,
       -3.51771699, -3.51337631, -3.5118571 , -3.50751642, -3.4285502 ,
       -3.42269031, -3.29187564, -3.28601575, -3.15227351, -3.14641362,
       -3.12721625, -3.12135636, -3.00461703, -2.99875714, -2.9013749 ,
       -2.89551501, -2.7672271 , -2.76177277, -2.76136721, -2.75591288,
       -2.64462788, -2.63876799, -2.541

# 2. Find the gnd state energy usong the power method

In [78]:
def random_state(Num):
    psi = np.random.rand(Num)
    psi /= np.linalg.norm(psi)
    check_psi(psi)
    return psi

psi = np.array([random_state(2**N)]).T
print(f'psi={psi}')

lamb = 8 # np.round(np.max(eigenresult.eigenvalues)+0.01,decimals=2)
print(f'lambda={lamb}')

print(f'H.shape={H.shape}')
H_prime = lamb*np.eye(2**N) - H
print(f'H_prime={H_prime}')

Ek=-999
iter = 0
while iter < 10000:
    psi1 = H_prime@psi
    print(f'psi.T @ psi1 {psi.T @ psi1 }')
    Ek1 =  np.sum(psi.T @ psi1) # np.sum( psi1.T @ H_prime @ psi1 ) # 
    print(f'Ek1={Ek1}')
    psi1 = psi1/np.linalg.norm(psi1)
    if np.abs(Ek - Ek1) < 1e-7:
        print(f'Found ground state: {lamb-Ek1:.4f}')
        break
    Ek = Ek1
    psi = psi1
    iter += 1




psi=[[0.00932607]
 [0.03124548]
 [0.07156151]
 [0.00141756]
 [0.04920867]
 [0.03254379]
 [0.10226586]
 [0.10194113]
 [0.08753286]
 [0.09513774]
 [0.0012717 ]
 [0.03856206]
 [0.08540728]
 [0.02262652]
 [0.04621388]
 [0.01183091]
 [0.06449308]
 [0.03267384]
 [0.0520872 ]
 [0.08783119]
 [0.09637211]
 [0.04472997]
 [0.07344545]
 [0.02227716]
 [0.05883547]
 [0.00805681]
 [0.00422192]
 [0.00195044]
 [0.08408999]
 [0.05643051]
 [0.03997265]
 [0.07629321]
 [0.04995969]
 [0.01408741]
 [0.09889252]
 [0.0390294 ]
 [0.07329058]
 [0.05800665]
 [0.03047341]
 [0.00880621]
 [0.02785548]
 [0.09205033]
 [0.1022218 ]
 [0.00352611]
 [0.10722898]
 [0.03787635]
 [0.09047101]
 [0.06324543]
 [0.01040404]
 [0.07231734]
 [0.00582468]
 [0.07343088]
 [0.0879557 ]
 [0.02010659]
 [0.04123287]
 [0.0148477 ]
 [0.10603285]
 [0.01462315]
 [0.01004431]
 [0.10251194]
 [0.05986676]
 [0.04413029]
 [0.09228891]
 [0.02871025]
 [0.09006343]
 [0.02902949]
 [0.03169471]
 [0.06914343]
 [0.09601597]
 [0.04300061]
 [0.01591523]
 [

# 3. Lindblad Master equation

In [ ]:
sigma_m = np.array([[0, 0],[1, 0]])
sigma_p = np.array([[0, 1],[0, 0]])

def sigma_k_i(sigma, k, Num):
    term1=None
    for j in range(Num-1):
        term_j = None
        for i in range(Num):
            term_i = None
            if (i == j):
                term_i = sigma
            else:
                term_i = identity
            
            if term_j is None:
                term_j = term_i
            else:
                term_j = np.kron(term_j, term_i)
        if term1 is None: term1 = term_j
        else: term1 += term_j
    return term1

def sigma_k_k1_i(sigma, k, Num):
    term1=None
    for j in range(Num-1):
        term_j = None
        for i in range(Num):
            term_i = None
            if (i == j or i == j+1):
                term_i = sigma
            else:
                term_i = identity
            
            if term_j is None:
                term_j = term_i
            else:
                term_j = np.kron(term_j, term_i)
        if term1 is None: term1 = term_j
        else: term1 += term_j
    return term1

Sz = sigma_k_i(pauliz, k, N)

SyntaxError: incomplete input (4191628920.py, line 2)