In [4]:
import numpy as np
import matplotlib.pyplot as plt
from math import pi
# import qutip as qu

state_0 = np.array([1,0])
state_1 = np.array([0,1])
print (state_0,'\n')
print (state_1,'\n')
X = np.array([[0,1],[1,0]])
H = (1/np.sqrt(2))*np.array([[1,1],[1,-1]]) # Hadamard gate
Y = np.array([[0,-1j],[1j,0]])
Z = np.array([[1,0],[0,-1]])
S = np.array([[1,0],[0,-1j]])
T = np.array([[1,0],[0,np.exp(1j*pi/4)]])

#def U(θ,α,β,φ):
#    return np.around(np.exp(1j*φ/2)*np.array([[np.exp(1j*α)*np.cos(θ), np.exp(1j*β)*[-1*np.exp(-1j*β)*np.sin(θ),np.exp(-1j*α)*np.cos(θ)]]]))

#print ("X =",U(pi/2,0,pi/2,-pi),'\n') # X from the general U(θ,ϕ,λ)
#print ("Y =",U(pi/2,0,0,-pi),'\n') # X from the general U(θ,ϕ,λ)

proj_0 = np.outer(state_0,state_0) # top half of the identity matrix
proj_1 = np.outer(state_1,state_1) # bottom half of the identity matrix
U_cnot = np.kron(proj_0,np.eye(2))+np.kron(proj_1,X)
print (U_cnot)

[1 0] 

[0 1] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [8]:
print (U_cnot@(np.kron(state_1,state_1)),'\n')
print (np.kron(state_1,state_0))
print('#'*20)
print (U_cnot@(np.kron(state_1,state_0)),'\n')
print (np.kron(state_1,state_1))
print('#'*20)
print (U_cnot@(np.kron(state_0,state_1)),'\n')
print (np.kron(state_0,state_1))
print('#'*20)
print (U_cnot@(np.kron(state_0,state_0)),'\n')
print (np.kron(state_0,state_0))
print('#'*20)

U_cnot@(np.kron(H@state_1,state_1)) # Entangled singlet state

[0. 0. 1. 0.] 

[0 0 1 0]
####################
[0. 0. 0. 1.] 

[0 0 0 1]
####################
[0. 1. 0. 0.] 

[0 1 0 0]
####################
[1. 0. 0. 0.] 

[1 0 0 0]
####################


array([ 0.        ,  0.70710678, -0.70710678,  0.        ])

In [9]:
U_H = np.kron(proj_0,np.eye(2))+np.kron(proj_1,H)
print (U_H)

[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.70710678  0.70710678]
 [ 0.          0.          0.70710678 -0.70710678]]


# Question 1. 
## Part 1- Write a function that creates the 3-qubit initial state

In [34]:
def threequbit(i, j, k):
    i1, i2, i3 = None, None, None
    if i == 0: i1 = state_0
    else: i1 = state_1
    if j == 0: i2 = state_0 
    else: i2 = state_1
    if k == 0: i3 = state_0 
    else: i3 = state_1
    return np.kron(i1, np.kron(i2, i3))



# Question 1. 
## Part 2- Write a function that implements the 3-qubit controlled-CNOT-CNOT gate

In [35]:


U_cnot3 = np.kron(proj_0,np.kron(np.eye(2),np.eye(2))) + np.kron(proj_1,np.kron(X,X))

print (U_cnot3@threequbit(1,1,1))
print (np.kron(state_1,np.kron(state_0,state_0)))
print('#'*20)

print (U_cnot3@threequbit(1,0,1))
print (np.kron(state_1,np.kron(state_1,state_0)))
print('#'*20)

print (U_cnot3@threequbit(1,0,0))
print (np.kron(state_1,np.kron(state_1,state_1)))
print('#'*20)

print (U_cnot3@threequbit(0,1,1))
print (np.kron(state_0,np.kron(state_1,state_1)))
print('#'*20)

print (U_cnot3@threequbit(0,0,1))
print (np.kron(state_0,np.kron(state_0,state_1)))
print('#'*20)

print (U_cnot3@threequbit(0,0,0))
print (np.kron(state_0,np.kron(state_0,state_0)))
print('#'*20)



[0. 0. 0. 0. 1. 0. 0. 0.]
[0 0 0 0 1 0 0 0]
####################
[0. 0. 0. 0. 0. 0. 1. 0.]
[0 0 0 0 0 0 1 0]
####################
[0. 0. 0. 0. 0. 0. 0. 1.]
[0 0 0 0 0 0 0 1]
####################
[0. 0. 0. 1. 0. 0. 0. 0.]
[0 0 0 1 0 0 0 0]
####################
[0. 1. 0. 0. 0. 0. 0. 0.]
[0 1 0 0 0 0 0 0]
####################
[1. 0. 0. 0. 0. 0. 0. 0.]
[1 0 0 0 0 0 0 0]
####################


# Question 1. 
## Part 3-  implement the circuit

In [36]:
np.kron(H,np.kron(np.eye(2),np.eye(2)))@U_cnot3@(np.kron(H@state_1,np.kron(state_1,state_1)))

array([-0.5,  0. ,  0. ,  0.5,  0.5,  0. ,  0. ,  0.5])

# Question 2. Rotation

In [49]:
def Rz(theta): 
    theta *= np.pi/180
    return np.array([[np.exp(-1j*theta/2), 0],[0, np.exp(1j*theta/2)]])

def rotation(theta=45,n=[1,0,0]):
    theta *= np.pi/180
    rn = np.cos(theta/2)*np.eye(2) - 1j*np.sin(theta/2)*(n[0]*X+n[1]*Y+n[2]*Z)
    return rn

print(rotation(45, [0,0,1])@state_0)
print(Rz(45)@state_0)

[0.92387953-0.38268343j 0.        +0.j        ]
[0.92387953-0.38268343j 0.        +0.j        ]


# Question 3. Measurement

In [59]:
def check(state):    
    print(np.sum(state**2) )
    if np.sum(state**2) > 1.01 or  np.sum(state**2) < 0.99:
        raise ValueError(np.sum(state**2) )

def Meas(state,mi):
    check(state)
    # |0,0> , |0, 1>, |1, 0> , |1,1>
    # collapse 1st qubit to state mi
    # Then renormalize the probability based on the possible states
    
    if mi == 0: # First bit measured and got outcome 0.
        state[2],state[3] = 0, 0
    else:
        state[0],state[1] = 0, 0

    # Renormalize
    # Sum squares of coefficients
    sum = np.sum(state**2)
    # Renormalize
    state *= 1/np.sqrt(sum)

    check(state)
    return state

state = np.array([0.5, 0.5, 0.5, 0.5])
print(f'state before measurement = {state}')
observed = 0
print(f'state after measurement - 1st bit collapse to {observed} = {Meas(state, observed)}')
print('#'*20)
state = np.array([0.5, 0.5, 0.5, 0.5])
print(f'state before measurement = {state}')
observed = 1
print(f'state after measurement - 1st bit collapse to {observed} = {Meas(state, observed)}')
print('#'*20)
state = np.array([0.5, 0.25, 0.5, 0.25*np.sqrt(7)])
print(f'state before measurement = {state}')
observed = 0
print(f'state after measurement - 1st bit collapse to {observed} = {Meas(state, observed)}')
print('#'*20)
state = np.array([0.5, 0.25, 0.5, 0.25*np.sqrt(7)])
print(f'state before measurement = {state}')
observed = 1
print(f'state after measurement - 1st bit collapse to {observed} = {Meas(state, observed)}')
print('#'*20)


state before measurement = [0.5 0.5 0.5 0.5]
1.0
0.9999999999999998
state after measurement - 1st bit collapse to 0 = [0.70710678 0.70710678 0.         0.        ]
####################
state before measurement = [0.5 0.5 0.5 0.5]
1.0
0.9999999999999998
state after measurement - 1st bit collapse to 1 = [0.         0.         0.70710678 0.70710678]
####################
state before measurement = [0.5        0.25       0.5        0.66143783]
1.0
0.9999999999999999
state after measurement - 1st bit collapse to 0 = [0.89442719 0.4472136  0.         0.        ]
####################
state before measurement = [0.5        0.25       0.5        0.66143783]
1.0
1.0
state after measurement - 1st bit collapse to 1 = [0.         0.         0.60302269 0.79772404]
####################
