In [5]:
import numpy as np
state0 = np.array([1,0])
state1 = np.array([0,1])
X = np.array([[0,1],[1,0]])
proj0=np.outer(state0, state0)
print(proj0)

proj1=np.outer(state1, state1)
print(proj1)

U_cnot = np.kron(proj0, np.eye(2)) + np.kron(proj1, X)
print(U_cnot)

[[1 0]
 [0 0]]
[[0 0]
 [0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
